language: go
go:
  - "1.13"

env:
  global:
    - GO111MODULE=on
matrix:
  include:
#    - name: "Codegen Check"
#      install:
#        - bash .scripts/install-protoc.sh
#        - bash .scripts/install-go-gen.sh
#        - go get -u golang.org/x/lint/golint
#        - GO111MODULE=on go mod vendor
#      script:
#        # generate code and exit with status 1 if diff is detected
#        - make proto
#        - git --no-pager diff
#        - git diff-index --quiet HEAD --

    - name: "Tests"
      install:
        - go get -u golang.org/x/lint/golint
        - GO111MODULE=on go mod vendor
      before_script:
        - go vet ./...
        - go test -run xxxx ./...
      script:
        - go fmt ./...
        - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
        - go test -race -timeout 5m -coverprofile=coverage.txt ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
