language: go
go:
  - "1.11"

matrix:
  include:
    - name: "Codegen Check"
      install:
        - bash .scripts/install-protoc.sh
        - go get -u github.com/golang/protobuf/protoc-gen-go
      script:
        # generate code and exit with status 1 if diff is detected
        - make proto
        - git --no-pager diff
        - git diff-index --quiet HEAD --

    - name: "Tests"
      language: go
      go:
        - "1.11"
      install:
        - go get -u golang.org/x/lint/golint
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure -v
      before_script:
        - go vet ./...
        - go test -run xxxx ./...
      script:
        - go fmt ./...
        - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
        - go test -race -timeout 5m -coverprofile=coverage.txt ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
